apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
  namespace: api-deployment-demo
  labels:
    app: api-demo
    component: api
    service-type: nodeport
spec:
  selector:
    app: api-demo
    component: api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30800
    protocol: TCP
  type: NodePort